INSERT INTO Tags(TagName, TagCount)
VALUES
	('cooking', 0),
	('cleaning' , 0),
	('mathematics', 0),
	('science', 0),
	('STEM', 0),
	('social studies', 0),
	('gender studies', 0),
	('physics', 0),
	('astrophysics', 0),
	('chemistry', 0),
	('english', 0),
	('literature', 0),
	('hobbies', 0),
	('DIY', 0),
	('cofee', 0),
	('tea', 0),
	('UI/UX', 0),
	('machine language', 0),
	('IDE', 0),
	('C#', 0),
	('java', 0),
	('python', 0),
	('graphic design', 0),
	('car', 0),
	('home improvement', 0),
	('credit score', 0),
	('software', 0),
	('cloud system', 0),
	('NFT', 0),
	('cryptocurrency', 0),
	('crypto', 0),
	('astrology', 0),
	('knitting', 0),
	('crocheting', 0),
	('budget', 0),
	('movie', 0),
	('solder', 0),
	('sports', 0),
	('taxes', 0),
	('law', 0),
	('food', 0),
	('haskell', 0),
	('art', 0),
	('snow', 0),
	('latin', 0),
	('motorcycle', 0),
	('bicycle', 0),
	('music', 0),
	('myth', 0),
	('ski', 0),
	('snowboard', 0),
	('acting', 0),
	('exercise', 0),
	('gym', 0),
	('fashion', 0),
	('nature', 0),
	('outdoor', 0),
	('gear', 0),
	('tennis', 0),
	('yoga', 0),
	('office', 0),
	('hike', 0),
	('rock', 0),
	('soda', 0),
	('book', 0),
	('film', 0),
	('garden', 0),
	('shop', 0),
	('life', 0),
	('map', 0),
	('podcast', 0),
	('radio', 0),
	('restaurant', 0),
	('tatoo', 0),
	('social media', 0),
	('influencer', 0),
	('beauty', 0),
	('beauty guru', 0),
	('makeup', 0),
	('eyeshadow', 0),
	('lipstick', 0),
	('nails', 0),
	('truck', 0),
	('dirt bike', 0),
	('surf', 0),
	('magazine', 0),
	('brunch', 0),
	('media', 0),
	('idea', 0),
	('firm', 0),
	('investing', 0),
	('reward', 0),
	('company', 0),
	('fortune 500', 0),
	('FANNG', 0),
	('time zone', 0),
	('identity', 0),
	('archery', 0),
	('rap', 0),
	('country', 0),
	('pop', 0),
	('DJ', 0),
	('furniture', 0),
	('woodworking', 0),
	('metal', 0),
	('love', 0),
	('comedy', 0), 
	('storytelling', 0),
	('craft', 0),
	('welding', 0),
	('sailing', 0),
	('travel', 0),
	('badminton', 0),
	('parasailing', 0),
	('skateboard', 0),
	('scooter', 0),
	('arm wrestling', 0),
	('space', 0),
	('calculus', 0),
	('algebra', 0),
	('geometry', 0),
	('XRAY', 0),
	('MRI', 0),
	('backyard', 0),
	('stairs', 0),
	('tools', 0),
	('document control', 0),
	('steak', 0),
	('fries', 0),
	('email', 0),
	('signature', 0),
	('workout', 0),
	('graduate school', 0),
	('thesis', 0),
	('agile', 0),
	('waterfall', 0),
	('scrum', 0),
	('free', 0),
	('no cost', 0),
	('gaming', 0)


